export const objects  = new Set([{}, { propertyA: 'b' }, { propertyA: 100, propertyB: 'c' }, { propertyA: 100500, propertyB: '200300', propertyC: { propertyD: 2 } }])
export const arrays   = new Set([[], [ 1, 2, 5, 7 ], [ 'abc', 123, true ]])
export const numbers  = new Set([0, 1, 100500, 0.0, 1.5, -10])
export const strings  = new Set(['', 'doge wow such much!', '12345', '0'])
export const booleans = new Set([true, false])
export const nullValues      = new Set([null])
export const undefinedValues = new Set([undefined])

export const primitives      = new Set([...numbers, ...strings, ...booleans])
export const definedValues   = new Set([...nullValues, ...primitives, ...objects, ...arrays])
export const anything        = new Set([...definedValues, ...undefinedValues])
